### PR TITLE
Add parameter support to MissionEditor.Console

### PR DESCRIPTION
**Pull request by abcdefg30**

### CODE REVIEW

**Comment by abcdefg30** [comment]
Updated.
We may want to add a kind of readme on how to compile the project.

**Comment by penev92** [comment]
What do you mean "how to compile"? There shouldn't be anything special required to do it.

**Comment by abcdefg30** [comment]
Like

```
Search the path to your MSBuild.exe
<Introduction on how to search>
Open the commandline and type:
(path_to_MSBuild.exe) MissionEditor.Console\MissionEditor.Console.csproj
(path_to_MSBuild.exe) MissionEditor.FileReaderCore\MissionEditor.FileReaderCore.csproj
(path_to_MSBuild.exe) MissionEditor.UI\MissionEditor.UI.csproj
```

**Comment by abcdefg30** [comment]
Updated.

**Comment by penev92** [comment]
Thanks!
Sorry for the delay.

**Pull request merged**
